# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from libs.common.grpc_gen import dataservice_pb2 as dataservice__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dataservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub:
    """============================================================================
    Data Service contract.

    The Data Service is the ONLY component with MySQL credentials. Every other
    service (worklist_api, engine, sync, scheduler) talks to it exclusively
    through this contract. Methods are grouped the same way the plan groups the
    Data Service's internal roles:
    - interactive read  : ListTasks, ListPatients, GetPatient, GetTask,
    ListPrograms, GetMeta
    - interactive write : ClaimTask, CompleteTask, DeclineTask, SnoozeTask
    - bulk               : StartSyncRun, UpsertFacts, CompleteSyncRun,
    GetPatientSnapshot, SaveEvaluationResult,
    EnqueueDuePatients, EnqueueAllPatients,
    ListSyncRuns
    The outbox relay is an internal loop with no RPC surface.
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMeta = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/GetMeta',
                request_serializer=dataservice__pb2.GetMetaRequest.SerializeToString,
                response_deserializer=dataservice__pb2.GetMetaResponse.FromString,
                _registered_method=True)
        self.ListPatients = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/ListPatients',
                request_serializer=dataservice__pb2.ListPatientsRequest.SerializeToString,
                response_deserializer=dataservice__pb2.ListPatientsResponse.FromString,
                _registered_method=True)
        self.GetPatient = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/GetPatient',
                request_serializer=dataservice__pb2.GetPatientRequest.SerializeToString,
                response_deserializer=dataservice__pb2.GetPatientResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/ListTasks',
                request_serializer=dataservice__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=dataservice__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/GetTask',
                request_serializer=dataservice__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=dataservice__pb2.GetTaskResponse.FromString,
                _registered_method=True)
        self.ListPrograms = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/ListPrograms',
                request_serializer=dataservice__pb2.ListProgramsRequest.SerializeToString,
                response_deserializer=dataservice__pb2.ListProgramsResponse.FromString,
                _registered_method=True)
        self.ClaimTask = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/ClaimTask',
                request_serializer=dataservice__pb2.ClaimTaskRequest.SerializeToString,
                response_deserializer=dataservice__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/CompleteTask',
                request_serializer=dataservice__pb2.CompleteTaskRequest.SerializeToString,
                response_deserializer=dataservice__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.DeclineTask = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/DeclineTask',
                request_serializer=dataservice__pb2.DeclineTaskRequest.SerializeToString,
                response_deserializer=dataservice__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.SnoozeTask = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/SnoozeTask',
                request_serializer=dataservice__pb2.SnoozeTaskRequest.SerializeToString,
                response_deserializer=dataservice__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.StartSyncRun = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/StartSyncRun',
                request_serializer=dataservice__pb2.StartSyncRunRequest.SerializeToString,
                response_deserializer=dataservice__pb2.StartSyncRunResponse.FromString,
                _registered_method=True)
        self.UpsertFacts = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/UpsertFacts',
                request_serializer=dataservice__pb2.UpsertFactsRequest.SerializeToString,
                response_deserializer=dataservice__pb2.UpsertFactsResponse.FromString,
                _registered_method=True)
        self.CompleteSyncRun = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/CompleteSyncRun',
                request_serializer=dataservice__pb2.CompleteSyncRunRequest.SerializeToString,
                response_deserializer=dataservice__pb2.CompleteSyncRunResponse.FromString,
                _registered_method=True)
        self.ListSyncRuns = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/ListSyncRuns',
                request_serializer=dataservice__pb2.ListSyncRunsRequest.SerializeToString,
                response_deserializer=dataservice__pb2.ListSyncRunsResponse.FromString,
                _registered_method=True)
        self.UpsertPrograms = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/UpsertPrograms',
                request_serializer=dataservice__pb2.UpsertProgramsRequest.SerializeToString,
                response_deserializer=dataservice__pb2.UpsertProgramsResponse.FromString,
                _registered_method=True)
        self.GetPatientSnapshot = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/GetPatientSnapshot',
                request_serializer=dataservice__pb2.GetPatientSnapshotRequest.SerializeToString,
                response_deserializer=dataservice__pb2.GetPatientSnapshotResponse.FromString,
                _registered_method=True)
        self.SaveEvaluationResult = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/SaveEvaluationResult',
                request_serializer=dataservice__pb2.SaveEvaluationResultRequest.SerializeToString,
                response_deserializer=dataservice__pb2.SaveEvaluationResultResponse.FromString,
                _registered_method=True)
        self.EnqueueDuePatients = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/EnqueueDuePatients',
                request_serializer=dataservice__pb2.EnqueueDuePatientsRequest.SerializeToString,
                response_deserializer=dataservice__pb2.EnqueueDuePatientsResponse.FromString,
                _registered_method=True)
        self.EnqueueAllPatients = channel.unary_unary(
                '/care_gap.dataservice.v1.DataService/EnqueueAllPatients',
                request_serializer=dataservice__pb2.EnqueueAllPatientsRequest.SerializeToString,
                response_deserializer=dataservice__pb2.EnqueueAllPatientsResponse.FromString,
                _registered_method=True)


class DataServiceServicer:
    """============================================================================
    Data Service contract.

    The Data Service is the ONLY component with MySQL credentials. Every other
    service (worklist_api, engine, sync, scheduler) talks to it exclusively
    through this contract. Methods are grouped the same way the plan groups the
    Data Service's internal roles:
    - interactive read  : ListTasks, ListPatients, GetPatient, GetTask,
    ListPrograms, GetMeta
    - interactive write : ClaimTask, CompleteTask, DeclineTask, SnoozeTask
    - bulk               : StartSyncRun, UpsertFacts, CompleteSyncRun,
    GetPatientSnapshot, SaveEvaluationResult,
    EnqueueDuePatients, EnqueueAllPatients,
    ListSyncRuns
    The outbox relay is an internal loop with no RPC surface.
    ============================================================================

    """

    def GetMeta(self, request, context):
        """--- interactive read ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPatients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPrograms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimTask(self, request, context):
        """--- interactive write (task state machine, optimistic locking) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclineTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnoozeTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSyncRun(self, request, context):
        """--- bulk (sync, engine, scheduler) ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertFacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteSyncRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSyncRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertPrograms(self, request, context):
        """The engine owns the YAML program loader; this persists what it parsed
        so "programs stored as data" is backed by MySQL, not just a file on
        disk, and GET /programs reflects it. Upsert is keyed by
        (program_id, version) — re-loading the same YAML changes nothing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatientSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveEvaluationResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueDuePatients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueAllPatients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeta,
                    request_deserializer=dataservice__pb2.GetMetaRequest.FromString,
                    response_serializer=dataservice__pb2.GetMetaResponse.SerializeToString,
            ),
            'ListPatients': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPatients,
                    request_deserializer=dataservice__pb2.ListPatientsRequest.FromString,
                    response_serializer=dataservice__pb2.ListPatientsResponse.SerializeToString,
            ),
            'GetPatient': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatient,
                    request_deserializer=dataservice__pb2.GetPatientRequest.FromString,
                    response_serializer=dataservice__pb2.GetPatientResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=dataservice__pb2.ListTasksRequest.FromString,
                    response_serializer=dataservice__pb2.ListTasksResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=dataservice__pb2.GetTaskRequest.FromString,
                    response_serializer=dataservice__pb2.GetTaskResponse.SerializeToString,
            ),
            'ListPrograms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPrograms,
                    request_deserializer=dataservice__pb2.ListProgramsRequest.FromString,
                    response_serializer=dataservice__pb2.ListProgramsResponse.SerializeToString,
            ),
            'ClaimTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimTask,
                    request_deserializer=dataservice__pb2.ClaimTaskRequest.FromString,
                    response_serializer=dataservice__pb2.TaskResponse.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=dataservice__pb2.CompleteTaskRequest.FromString,
                    response_serializer=dataservice__pb2.TaskResponse.SerializeToString,
            ),
            'DeclineTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclineTask,
                    request_deserializer=dataservice__pb2.DeclineTaskRequest.FromString,
                    response_serializer=dataservice__pb2.TaskResponse.SerializeToString,
            ),
            'SnoozeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SnoozeTask,
                    request_deserializer=dataservice__pb2.SnoozeTaskRequest.FromString,
                    response_serializer=dataservice__pb2.TaskResponse.SerializeToString,
            ),
            'StartSyncRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSyncRun,
                    request_deserializer=dataservice__pb2.StartSyncRunRequest.FromString,
                    response_serializer=dataservice__pb2.StartSyncRunResponse.SerializeToString,
            ),
            'UpsertFacts': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertFacts,
                    request_deserializer=dataservice__pb2.UpsertFactsRequest.FromString,
                    response_serializer=dataservice__pb2.UpsertFactsResponse.SerializeToString,
            ),
            'CompleteSyncRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteSyncRun,
                    request_deserializer=dataservice__pb2.CompleteSyncRunRequest.FromString,
                    response_serializer=dataservice__pb2.CompleteSyncRunResponse.SerializeToString,
            ),
            'ListSyncRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSyncRuns,
                    request_deserializer=dataservice__pb2.ListSyncRunsRequest.FromString,
                    response_serializer=dataservice__pb2.ListSyncRunsResponse.SerializeToString,
            ),
            'UpsertPrograms': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertPrograms,
                    request_deserializer=dataservice__pb2.UpsertProgramsRequest.FromString,
                    response_serializer=dataservice__pb2.UpsertProgramsResponse.SerializeToString,
            ),
            'GetPatientSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientSnapshot,
                    request_deserializer=dataservice__pb2.GetPatientSnapshotRequest.FromString,
                    response_serializer=dataservice__pb2.GetPatientSnapshotResponse.SerializeToString,
            ),
            'SaveEvaluationResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveEvaluationResult,
                    request_deserializer=dataservice__pb2.SaveEvaluationResultRequest.FromString,
                    response_serializer=dataservice__pb2.SaveEvaluationResultResponse.SerializeToString,
            ),
            'EnqueueDuePatients': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueDuePatients,
                    request_deserializer=dataservice__pb2.EnqueueDuePatientsRequest.FromString,
                    response_serializer=dataservice__pb2.EnqueueDuePatientsResponse.SerializeToString,
            ),
            'EnqueueAllPatients': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueAllPatients,
                    request_deserializer=dataservice__pb2.EnqueueAllPatientsRequest.FromString,
                    response_serializer=dataservice__pb2.EnqueueAllPatientsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'care_gap.dataservice.v1.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('care_gap.dataservice.v1.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService:
    """============================================================================
    Data Service contract.

    The Data Service is the ONLY component with MySQL credentials. Every other
    service (worklist_api, engine, sync, scheduler) talks to it exclusively
    through this contract. Methods are grouped the same way the plan groups the
    Data Service's internal roles:
    - interactive read  : ListTasks, ListPatients, GetPatient, GetTask,
    ListPrograms, GetMeta
    - interactive write : ClaimTask, CompleteTask, DeclineTask, SnoozeTask
    - bulk               : StartSyncRun, UpsertFacts, CompleteSyncRun,
    GetPatientSnapshot, SaveEvaluationResult,
    EnqueueDuePatients, EnqueueAllPatients,
    ListSyncRuns
    The outbox relay is an internal loop with no RPC surface.
    ============================================================================

    """

    @staticmethod
    def GetMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/GetMeta',
            dataservice__pb2.GetMetaRequest.SerializeToString,
            dataservice__pb2.GetMetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPatients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/ListPatients',
            dataservice__pb2.ListPatientsRequest.SerializeToString,
            dataservice__pb2.ListPatientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/GetPatient',
            dataservice__pb2.GetPatientRequest.SerializeToString,
            dataservice__pb2.GetPatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/ListTasks',
            dataservice__pb2.ListTasksRequest.SerializeToString,
            dataservice__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/GetTask',
            dataservice__pb2.GetTaskRequest.SerializeToString,
            dataservice__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPrograms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/ListPrograms',
            dataservice__pb2.ListProgramsRequest.SerializeToString,
            dataservice__pb2.ListProgramsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/ClaimTask',
            dataservice__pb2.ClaimTaskRequest.SerializeToString,
            dataservice__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/CompleteTask',
            dataservice__pb2.CompleteTaskRequest.SerializeToString,
            dataservice__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeclineTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/DeclineTask',
            dataservice__pb2.DeclineTaskRequest.SerializeToString,
            dataservice__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnoozeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/SnoozeTask',
            dataservice__pb2.SnoozeTaskRequest.SerializeToString,
            dataservice__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSyncRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/StartSyncRun',
            dataservice__pb2.StartSyncRunRequest.SerializeToString,
            dataservice__pb2.StartSyncRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertFacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/UpsertFacts',
            dataservice__pb2.UpsertFactsRequest.SerializeToString,
            dataservice__pb2.UpsertFactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteSyncRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/CompleteSyncRun',
            dataservice__pb2.CompleteSyncRunRequest.SerializeToString,
            dataservice__pb2.CompleteSyncRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSyncRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/ListSyncRuns',
            dataservice__pb2.ListSyncRunsRequest.SerializeToString,
            dataservice__pb2.ListSyncRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertPrograms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/UpsertPrograms',
            dataservice__pb2.UpsertProgramsRequest.SerializeToString,
            dataservice__pb2.UpsertProgramsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatientSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/GetPatientSnapshot',
            dataservice__pb2.GetPatientSnapshotRequest.SerializeToString,
            dataservice__pb2.GetPatientSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveEvaluationResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/SaveEvaluationResult',
            dataservice__pb2.SaveEvaluationResultRequest.SerializeToString,
            dataservice__pb2.SaveEvaluationResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueDuePatients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/EnqueueDuePatients',
            dataservice__pb2.EnqueueDuePatientsRequest.SerializeToString,
            dataservice__pb2.EnqueueDuePatientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueAllPatients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/care_gap.dataservice.v1.DataService/EnqueueAllPatients',
            dataservice__pb2.EnqueueAllPatientsRequest.SerializeToString,
            dataservice__pb2.EnqueueAllPatientsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
