"""Initial schema: all 13 tables from the MVP plan.

Revision ID: 0001
Revises:
Create Date: 2026-09-26

Hand-written rather than autogenerated so the `tasks.open_key` generated
column and its unique index match the plan's DDL exactly — MySQL has no
partial indexes, so this generated-column trick is what gives us "one open
task per patient/program/specialty" while still keeping closed history.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "patients",
        sa.Column("patient_id", sa.String(16), primary_key=True),
        sa.Column("first_name", sa.String(80), nullable=False),
        sa.Column("last_name", sa.String(80), nullable=False),
        sa.Column("date_of_birth", sa.Date, nullable=False),
        sa.Column("gender", sa.String(16), nullable=False),
        sa.Column("phone", sa.String(32), nullable=False),
        sa.Column("language", sa.String(40), nullable=False),
        sa.Column("pcp_provider_name", sa.String(120), nullable=True),
        sa.Column("row_hash", sa.String(64), nullable=False),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
        sa.Column(
            "updated_at", sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()
        ),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )

    op.create_table(
        "diagnoses",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column(
            "patient_id", sa.String(16), sa.ForeignKey("patients.patient_id"), nullable=False
        ),
        sa.Column("icd_code", sa.String(16), nullable=False),
        sa.Column("description", sa.String(255), nullable=False),
        sa.Column("diagnosed_date", sa.Date, nullable=False),
        sa.Column("row_hash", sa.String(64), nullable=False),
        sa.UniqueConstraint(
            "patient_id", "icd_code", "diagnosed_date", name="uq_diagnosis_natural_key"
        ),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_diagnoses_patient", "diagnoses", ["patient_id"])

    op.create_table(
        "labs",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column(
            "patient_id", sa.String(16), sa.ForeignKey("patients.patient_id"), nullable=False
        ),
        sa.Column("test_name", sa.String(80), nullable=False),
        sa.Column("result_value", sa.Numeric(8, 2), nullable=False),
        sa.Column("result_date", sa.Date, nullable=False),
        sa.Column("row_hash", sa.String(64), nullable=False),
        sa.UniqueConstraint(
            "patient_id", "test_name", "result_date", name="uq_lab_natural_key"
        ),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_labs_patient", "labs", ["patient_id"])

    op.create_table(
        "encounters",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column(
            "patient_id", sa.String(16), sa.ForeignKey("patients.patient_id"), nullable=False
        ),
        sa.Column("specialty", sa.String(40), nullable=False),
        sa.Column("encounter_date", sa.Date, nullable=False),
        sa.Column("provider_name", sa.String(120), nullable=False),
        sa.Column("row_hash", sa.String(64), nullable=False),
        sa.UniqueConstraint(
            "patient_id",
            "specialty",
            "encounter_date",
            "provider_name",
            name="uq_encounter_natural_key",
        ),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index(
        "ix_encounters_patient_specialty_date",
        "encounters",
        ["patient_id", "specialty", "encounter_date"],
    )

    op.create_table(
        "programs",
        sa.Column("program_id", sa.String(40), primary_key=True),
        sa.Column("version", sa.Integer, primary_key=True),
        sa.Column("definition", sa.JSON, nullable=False),
        sa.Column("active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("loaded_at", sa.DateTime, server_default=sa.func.now()),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )

    op.create_table(
        "enrollments",
        sa.Column(
            "patient_id", sa.String(16), sa.ForeignKey("patients.patient_id"), primary_key=True
        ),
        sa.Column("program_id", sa.String(40), primary_key=True),
        sa.Column("tier", sa.String(40), nullable=False),
        sa.Column("program_version", sa.Integer, nullable=False),
        sa.Column("evaluated_at", sa.DateTime, nullable=False),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )

    op.create_table(
        "needs",
        sa.Column(
            "patient_id", sa.String(16), sa.ForeignKey("patients.patient_id"), primary_key=True
        ),
        sa.Column("program_id", sa.String(40), primary_key=True),
        sa.Column("specialty", sa.String(40), primary_key=True),
        sa.Column("cadence_days", sa.Integer, nullable=False),
        sa.Column("last_visit_date", sa.Date, nullable=True),
        sa.Column("due_date", sa.Date, nullable=True),
        sa.Column("has_upcoming", sa.Boolean, nullable=False, server_default=sa.false()),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )

    # tasks — copied from the plan's DDL verbatim (generated column + unique
    # index for "one open task per key").
    op.execute(
        """
        CREATE TABLE tasks (
          task_id       BIGINT AUTO_INCREMENT PRIMARY KEY,
          patient_id    VARCHAR(16) NOT NULL,
          program_id    VARCHAR(40) NOT NULL,
          specialty     VARCHAR(40) NOT NULL,
          task_type     ENUM('scheduling','referral') NOT NULL,
          status        ENUM('open','in_progress','completed','declined','closed') NOT NULL DEFAULT 'open',
          due_date      DATE NULL,
          snooze_until  DATE NULL,
          resolution    VARCHAR(40) NULL,
          assigned_to   VARCHAR(64) NULL,
          program_version INT NOT NULL,
          version       INT NOT NULL DEFAULT 1,
          created_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
          updated_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
          open_key VARCHAR(80) GENERATED ALWAYS AS (
            IF(status IN ('open','in_progress'), CONCAT(patient_id,'|',program_id,'|',specialty), NULL)
          ) STORED,
          CONSTRAINT fk_tasks_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
          UNIQUE KEY uq_one_open_task (open_key),
          KEY ix_worklist (status, task_type, specialty, due_date),
          KEY ix_task_patient (patient_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
        """
    )

    op.create_table(
        "patient_eval_state",
        sa.Column(
            "patient_id", sa.String(16), sa.ForeignKey("patients.patient_id"), primary_key=True
        ),
        sa.Column("next_eval_at", sa.DateTime, nullable=True),
        sa.Column("last_evaluated_at", sa.DateTime, nullable=True),
        sa.Column("last_idempotency_key", sa.String(64), nullable=True),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index(
        "ix_eval_state_next_eval_at", "patient_eval_state", ["next_eval_at"]
    )

    op.create_table(
        "outbox",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("event_id", sa.String(36), nullable=False, unique=True),
        sa.Column("topic", sa.String(80), nullable=False),
        sa.Column("event_key", sa.String(40), nullable=False),
        sa.Column("payload", sa.JSON, nullable=False),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
        sa.Column("published_at", sa.DateTime, nullable=True),
        sa.Column("attempts", sa.Integer, nullable=False, server_default="0"),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_outbox_published_id", "outbox", ["published_at", "id"])

    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("event_id", sa.String(36), nullable=False, unique=True),
        sa.Column("occurred_at", sa.DateTime, server_default=sa.func.now()),
        sa.Column("actor", sa.String(64), nullable=False),
        sa.Column("action", sa.String(60), nullable=False),
        sa.Column("entity", sa.String(40), nullable=False),
        sa.Column("patient_id", sa.String(16), nullable=True),
        sa.Column("before_json", sa.JSON, nullable=True),
        sa.Column("after_json", sa.JSON, nullable=True),
        sa.Column("request_id", sa.String(40), nullable=False),
        sa.Column("result", sa.String(20), nullable=False),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_audit_patient", "audit_events", ["patient_id"])
    op.create_index("ix_audit_entity", "audit_events", ["entity"])

    op.create_table(
        "sync_runs",
        sa.Column("run_id", sa.String(36), primary_key=True),
        sa.Column("source", sa.String(20), nullable=False, server_default="csv"),
        sa.Column("status", sa.String(20), nullable=False, server_default="running"),
        sa.Column("started_at", sa.DateTime, server_default=sa.func.now()),
        sa.Column("finished_at", sa.DateTime, nullable=True),
        sa.Column("counts_json", sa.JSON, nullable=False),
        sa.Column("watermarks_json", sa.JSON, nullable=False),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )

    op.create_table(
        "sync_quarantine",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column(
            "run_id", sa.String(36), sa.ForeignKey("sync_runs.run_id"), nullable=False
        ),
        sa.Column("resource_type", sa.String(20), nullable=False),
        sa.Column("raw_row", sa.JSON, nullable=False),
        sa.Column("reason", sa.String(255), nullable=False),
        sa.Column("created_at", sa.DateTime, server_default=sa.func.now()),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index("ix_quarantine_run", "sync_quarantine", ["run_id"])

    op.create_table(
        "staging_rows",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("run_id", sa.String(36), nullable=False),
        sa.Column("resource_type", sa.String(20), nullable=False),
        sa.Column("chunk_number", sa.Integer, nullable=False),
        sa.Column("natural_key", sa.String(160), nullable=False),
        sa.Column("row_hash", sa.String(64), nullable=False),
        sa.Column("fields", sa.JSON, nullable=False),
        mysql_engine="InnoDB",
        mysql_charset="utf8mb4",
    )
    op.create_index(
        "ix_staging_run_chunk", "staging_rows", ["run_id", "resource_type", "chunk_number"]
    )
    op.create_index(
        "ix_staging_natural_key", "staging_rows", ["resource_type", "natural_key"]
    )


def downgrade() -> None:
    op.drop_table("staging_rows")
    op.drop_table("sync_quarantine")
    op.drop_table("sync_runs")
    op.drop_table("audit_events")
    op.drop_table("outbox")
    op.drop_table("patient_eval_state")
    op.drop_table("tasks")
    op.drop_table("needs")
    op.drop_table("enrollments")
    op.drop_table("programs")
    op.drop_table("encounters")
    op.drop_table("labs")
    op.drop_table("diagnoses")
    op.drop_table("patients")
